<?php if(!empty($messageError)): ?>
<div class="row">
    <div class="alert alert-warning page-alert" id="alert-3">
        <button type="button" class="close"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        <strong>Warning!</strong> <?= $messageError ?>
    </div>
</div>
<?php else: ?>

<div class="span3 well">
    <center>
        <a href="#aboutModal" data-toggle="modal" data-target="#myModal">
            <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRbezqZpEuwGSvitKy3wrwnth5kysKdRqBW54cAszm_wiutku3R" name="aboutme" width="140" height="140" class="img-circle"></a>
        <h3><?= $user->getFullName() ?></h3>
        <em>click my face for more</em>
        <center>
            <a href="<?= $this->url('admin/user') ?>" class="btn btn-default">Voltar</a>
        </center>
    </center>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title" id="myModalLabel">More About <?= $user->getFullName() ?></h4>
            </div>
            <div class="modal-body">
                <center>
                    <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRbezqZpEuwGSvitKy3wrwnth5kysKdRqBW54cAszm_wiutku3R" name="aboutme" width="140" height="140" border="0" class="img-circle"></a>
                    <h3 class="media-heading"><?= $user->getFullName() ?></h3>
                    <span><strong>Skills: </strong></span>
                    <span class="label label-warning">HTML5/CSS</span>
                    <span class="label label-info">Adobe CS 5.5</span>
                    <span class="label label-info">Microsoft Office</span>
                    <span class="label label-success">Windows XP, Vista, 7</span>
                </center>
                <hr>
                <center>
                    <p class="text-left"><strong>Dados Pessoas: </strong><br>
                        <b>Email:</b><?= $user->getEmail() ?><br/>
                        <b>Perfis:</b><?= $user->getRolesString() ?><br/>
                        <b>Status:</b><?= $user->getStatus() == 1 ?  "ATIVO" : "INATIVO" ?><br/>
                        </p>
                    <br>
                </center>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>