<div class="row">
    <div class="span4 well">
        <div class="row">
            <div class="span3">
                <p><?= $resource->getAction() ?></p>
                <p><strong><?= $resource->getDescription() ?></strong></p>
                <span class=" badge badge-warning">8 messages</span> <span class=" badge badge-info">15 followers</span>
            </div>
        </div>
    </div>
</div>